### ISSUE TITLE
Add support for battery information?

### ISSUE THREAD

**Issue by JS-E** [williamahartman/Jamepad#30]
Hey there,

Love Jamepad and have been using it to build a little test application. I'd like to help add more stuff to it as i'm a java dev and one feature i'd like is the ability to see the battery data (level etc) 

If someone could point me in the right direction of how this might be retrieved i'll gladly take a look and potentially add it :)

Thanks!

**Comment by electronstudio** [comment]
You would need to wrap https://wiki.libsdl.org/SDL_JoystickCurrentPowerLevel

I'm not developing Jamepad further because I moved on to sdl2gdx, but I can easily add this to the next release of sdl2gdx.

**Comment by JS-E** [comment]
Thanks for the reply, so i noticed in the Jamepad code you've used some native methods to run certain elements, can i reuse these to do a similar thing with the info in the link you've provided?

Yeah i am aware you've moved away from this project but i'm quite keen on it's simplicity. Will sdl2gdx be ever integrated into another Jamepad like library?

**Comment by electronstudio** [comment]
The code is BSD licensed so yes you can reuse it however you like.

The idea of sdl2gdx is to be simpler than Jamepad.  With sdl2gdx you don't have to worry about managing ControllerState objects that may be out of date.  You don't have to worry that anything will throw an exception because a controller was unplugged.  You just get given a list of Controller objects and query them: https://electronstudio.github.io/sdl2gdx/uk/co/electronstudio/sdl2gdx/SDL2Controller.

If you let me know in what way you would you like sdl2gdx to be more Jamepad like I will see what I can do? :-)

**Comment by electronstudio** [comment]
I have now added a method to get powerlevel in sdl2gdx.  It doesn't seem to be supported on MacOS so not sure how useful it will be.  It should be in the next release soon.

**Comment by electronstudio** [comment]
It works on Windows.  Not supported on Linux.

**Comment by JS-E** [comment]
Awesome! Thanks for getting it in so quickly :D

I think the way you've explained how to add it to gradle and examples make it very clear and attractive to developers, that's the reason why i wanted to use it. Documentation on a library is very important to be and your examples were incredibly straight forward and i got it up and running in no time at all.

I think the sdl2gdx documentation doesn't seem as straight forward as Jamepad and i think that puts me off. Having the one gradle dependancy and then examples makes a lot more sense to me personally. Hopefully that makes sense

**Comment by electronstudio** [comment]
I guess that's because William Hartman, the original author of Jamepad, is better at writing documentation than I am.  I will see what I can do to copy the Jamepad doc style.  sdl2gdx is also just one gradle dependeancy though, and it's 100% compatible with libGDX so you could  read the libGDX controller tutorial.

If the Jamepad API really is more attractive than the sdl2gdx API I guess people will continue to use it.  Perhaps I could rewrite Jamepad so it's just a wrapper around sdl2gdx and then it would never require any more maintainence but would benefit from future releases of sdl2gdx.

**Comment by JS-E** [comment]
Ah i see, in that case it might just be me not reading your docs correctly. I am interested in sdl2gdx as some of the features it has Jamepad doesn't and i'm keen to try and help out if needs be. 

If you did do that, i do think it'll be awesome. I'd happily help out where i can as i have a lot of uses for this library and i think it's going in a really cool direction :D

**Comment by electronstudio** [comment]
New release of Jamepad that is a wrapper around sdl2gdx.

New release of sdl2gdx that has the power level feature: https://electronstudio.github.io/sdl2gdx/uk/co/electronstudio/sdl2gdx/SDL2Controller.html#getPowerLevel--
